### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Happy0/ssb-bluetooth#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Happy0** [comment]
how lovely :3. Feel free! I'm not sure where I could display it other than on this github repo, is the only thing. Maybe people will like it and will use it for the UI for the bluetooth functionality of their scuttlebutt applications?

What license would the logo fall under?

**Comment by mansya** [comment]
this logo is under the creativecommons license. can you explain what ssb is? and create a README.md file (like someone else's project readme) in your project?

**Comment by mansya** [comment]
hi sir. I have designed a logo for your project. What do you think ? do you like it ? if yes. please tell me.
![ssb bluetooth](https://user-images.githubusercontent.com/33461607/48013072-188b0080-e156-11e8-9686-41921b718915.png)

**Comment by Happy0** [comment]
Thanks very much @mansya =]. I shall put it in the Read Me soon.

Sorry I didn't answer your question asking for more information about the protocol. Have you heard of scuttlebutt? https://www.scuttlebutt.nz/ . This project is to allow people to connect their two devices together using bluetooth to synchronize their social network data, without requiring the Internet or a network connection.

**Comment by mansya** [comment]
I will make a pull request to you and will give you all the files immediately. you can wait for a moment

**Comment by Happy0** [comment]
If you're up for another challenge, https://github.com/ssbc/patchbay is currently looking for another icon to distinguish it from https://github.com/ssbc/patchwork .

Relevant thread: https://github.com/ssbc/patchbay/issues/215

**Comment by mansya** [comment]
I have sent you [**pull  requests.**](https://github.com/Happy0/ssb-bluetooth/pull/2) please check. and I have also uploaded all the files to this [**Drive.**](https://drive.google.com/open?id=1MOh17ib0LA37NMQs2MwLico5VB061f6c)

and about this [project](https://github.com/ssbc/patchbay) I will contact him now.
